#!/bin/bash

# Create docker volume for n8n data
docker volume create n8n_data

# Run n8n container
docker run -it --rm \
 --name n8n \
 -p 5678:5678 \
 -e GENERIC_TIMEZONE="$(timedatectl | grep "Time zone" | awk '{print $3}')" \
 -e TZ="$(timedatectl | grep "Time zone" | awk '{print $3}')" \
 -e N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true \
 -e N8N_RUNNERS_ENABLED=true \
 -v n8n_data:/home/node/.n8n \
 docker.n8n.io/n8nio/n8n
